### ISSUE TITLE
Define peach-config CLI

### ISSUE THREAD

**Issue by mhfowler** [peachcloud/peach-config#34]
Now that this is module, was thinking about what its API should be.

Here is a draft:
``` 
peach-config update-self : updates peach-config only
peach-config update : updates peach-config, then updates all other micro services (in the future also runs any migrations if needed), then runs peach-config setup (using whatever arguments were used last time this was called)
peach-config setup -i -r ds3231 peach : idempotent script which configures all system files and settings based on flags 
peach-config --version : returns current version of peach-config
peach-config manifest : returns a json of the current version of installed microservices, and the last configurations that were used for peach-config setup. 
```

@mycognosist let me know if you have any revisions? I kind of just spitballed this. 

We could also consider to rename this CLI tool to just `peach`. I believe this is the route home-assistant took (their CLI tool is called "ha" and different functions are subcommands). Similarly with yunohost their CLI tool is called yunohost, and different functions are subcommands of this command. 

But I also like peach-config, its also nice that it shows peach-config is a specific tool.

**Comment by mycognosist** [comment]
@mhfowler 

The proposed API looks solid to me. I think you've covered the bases in terms of functionality. The `manifest` feature is really nice. I can imagine that providing a neat route to backing-up a `peach` or transitioning from one machine to another.

I'm happy to keep the `peach-config` name for now. Perhaps at a later stage we'll bundle in more functionality and it'll make more sense to have `peach` as the entry-point, with config-related features as a subset.
