### ISSUE TITLE
Change peach-config github "about" section

### ISSUE THREAD

**Issue by mhfowler** [peachcloud/peach-config#35]
I would like to change this about section to say

"Python module which handles installation and updating for PeachCloud."

which I think fits what this repo is more now. 

But I think I don't have permissions right now to edit the About section for this repo (cc @mycognosist)

**Comment by mycognosist** [comment]
@mhfowler 

I've updated the permissions. I believe you should be able to edit repository settings now. I have updated the About section for you in the meantime.
